title: VOLVOregister.nl
email: info@VOLVOregister.nl
description: "Wij geloven dat elke VOLVO uniek is en het verdient erkend te worden door zijn gelijken. Het VOLVO Register dient als een bron voor VOLVO liefhebbers om aanvullende informatie te verkrijgen over specifieke modellen."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title/
twitter_username: # VOLVOregister
github_username:  VOLVOregister

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
